### ISSUE TITLE
nbdmount doesn't properly start anymore with extra volumes

### ISSUE THREAD

**Issue by aimxhaisse** [EvaSDK/labs.online.net-gentoo-image#1]
Few things that seem broken :
- The 3.17 kernel has no nbd module, it is built in the kernel, `nbdmount` should not use `modprobe` to check if there's NBD support (maybe via `zcat /proc/config.gz`?)
- `nbdmount start/stop` should not try to connect/disconnect nbd0 (since it's handled via initramfs)
- `/etc/nbdtab` is not properly generated (extra `'`, something changed in the metadata?):
  
     $ cat /etc/nbdtab
      /dev/nbd'1    raw
      /dev/nbd0'    raw

cc @moul

**Comment by aimxhaisse** [comment]
Also, maybe we should consider using `xnbd-client`, since that's what is used in the initramfs, and what we consider as being stable.

**Comment by brmzkw** [comment]
For the extra ', I guess it comes from the recent update of the metadata API that fixed the quoting issue with lists and dicts.

**Comment by EvaSDK** [comment]
- The nbdmount init script is heavily inspired by the nfsmount script. I do not wish to modify the way it works since I do not want to be tied to `cloud.online.net` more than necessary.
- The root volume is properly ignored for stop which is sufficient as checking if it is connecting on start does no harm.
- The quoting issue is indeed due to metadata API changes. I have a fix for that that I need to push.
- xnbd-client is not packaged in Gentoo. There is an open bug report for this and I plan on testing it, but this is not a requirement for a working image for now.

**Comment by EvaSDK** [comment]
As for the real issue that is non-root NBD volumes not being started on boot, this is a concern I have raised multiple times already.

Volumes not being available when the instance is powered up makes it useless. You are likely to store data that is needed to operate your image. There is no point in booting fast if you still have to wait one or two hours for the rest of the data to be transfered to do anything useful.

**Comment by EvaSDK** [comment]
There are ways to make services start but be marked as inactive until the service itself completes startup (like NetworkManager) but due to the way mounting devices is designed in Linux distributions, I feel this is an inappropriate use of this feature. _labs.online.net_ should provide a way to have all disks available before the system is actually booted.
